---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-sample-linux-deployment
  # namespace: eks-sample-app
  labels:
    app: eks-sample-linux-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-sample-linux-app
  template:
    metadata:
      labels:
        app: eks-sample-linux-app
    spec:
      # affinity:
        # nodeAffinity:
        #   requiredDuringSchedulingIgnoredDuringExecution:
        #     nodeSelectorTerms:
        #     - matchExpressions:
        #       - key: kubernetes.io/arch
        #         operator: In
        #         values:
        #         - amd64
        #         - arm64
      containers:
      - name: nginx
        image: 986542577270.dkr.ecr.ap-south-1.amazonaws.com/deploytoecs
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
